// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALNEgLILMOha7EiUxL-NcPUNvTvbKkDbw',
    appId: '1:559644958173:web:2daa28805b482c99246a34',
    messagingSenderId: '559644958173',
    projectId: 'tasker-a7722',
    authDomain: 'tasker-a7722.firebaseapp.com',
    storageBucket: 'tasker-a7722.firebasestorage.app',
    measurementId: 'G-0EFZ3B5BH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiMocz4otCHOa90jupzLpY6p17Sb3BMN8',
    appId: '1:559644958173:android:d7e3b6df6dcbd9cd246a34',
    messagingSenderId: '559644958173',
    projectId: 'tasker-a7722',
    storageBucket: 'tasker-a7722.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtfiGVLik_2gANfEN1-C8yKZvdlmB-5g4',
    appId: '1:559644958173:ios:4a16410648e3a837246a34',
    messagingSenderId: '559644958173',
    projectId: 'tasker-a7722',
    storageBucket: 'tasker-a7722.firebasestorage.app',
    iosBundleId: 'com.example.tasker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtfiGVLik_2gANfEN1-C8yKZvdlmB-5g4',
    appId: '1:559644958173:ios:4a16410648e3a837246a34',
    messagingSenderId: '559644958173',
    projectId: 'tasker-a7722',
    storageBucket: 'tasker-a7722.firebasestorage.app',
    iosBundleId: 'com.example.tasker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALNEgLILMOha7EiUxL-NcPUNvTvbKkDbw',
    appId: '1:559644958173:web:8579ab71ada6a2af246a34',
    messagingSenderId: '559644958173',
    projectId: 'tasker-a7722',
    authDomain: 'tasker-a7722.firebaseapp.com',
    storageBucket: 'tasker-a7722.firebasestorage.app',
    measurementId: 'G-GJNPHTNK9W',
  );
}
